DROP TABLE ODONTOLOGO IF EXISTS;
CREATE TABLE ODONTOLOGO(
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL
);

INSERT INTO ODONTOLOGO VALUES(DEFAULT, 12345, 'ANDRES', 'FERRADA');
INSERT INTO ODONTOLOGO VALUES(DEFAULT, 67890, 'ELIAS', 'HERNANDEZ');
